// Generated by CoffeeScript 1.7.1
(function() {
  var $, a, defaultControls, getWebGL, hasWebGL, init, s, u, _fn, _i, _len;

  $ = function(_) {
    return document.getElementById(_);
  };

  init = function(controlType, quality, hud, godmode) {
    var hexGL, progressbar;
    
    // --- SAMSUNG/ANDROID FIX: Stop the browser from interfering ---
    document.addEventListener('touchstart', function(e) { e.preventDefault(); }, {passive: false});
    
    hexGL = new bkcore.hexgl.HexGL({
      document: document,
      width: window.innerWidth,
      height: window.innerHeight,
      container: $('main'),
      overlay: $('overlay'),
      gameover: $('step-5'),
      quality: quality,
      difficulty: 0,
      hud: hud === 1,
      controlType: controlType,
      godmode: godmode,
      track: 'Cityscape'
    });
    window.hexGL = hexGL;
    progressbar = $('progressbar');
    return hexGL.load({
      onLoad: function() {
        hexGL.init();
        $('step-3').style.display = 'none';
        $('step-4').style.display = 'block';
        return hexGL.start();
      },
      onError: function(s) { return console.error("Error: " + s); },
      onProgress: function(p, t, n) {
        return progressbar.style.width = "" + (p.loaded / p.total * 100) + "%";
      }
    });
  };

  u = bkcore.Utils.getURLParameter;

  // --- FORCE TOUCH FOR SAMSUNG GALAXY TABS ---
  defaultControls = 1; // Since it's your tablet, let's just force Touch mode on by default.

  s = [
    ['controlType', ['KEYBOARD', 'TOUCH', 'LEAP', 'GAMEPAD'], defaultControls, defaultControls, 'Controls: '],
    ['quality', ['LOW', 'MID', 'HIGH', 'VERY HIGH'], 0, 0, 'Quality: '], // Default to LOW for smoother Android FPS
    ['hud', ['OFF', 'ON'], 1, 1, 'HUD: '],
    ['godmode', ['OFF', 'ON'], 0, 1, 'Godmode: ']
  ];

  _fn = function(a) {
    var e, f, _ref;
    a[3] = (_ref = u(a[0])) != null ? _ref : a[2];
    e = $("s-" + a[0]);
    (f = function() { return e.innerHTML = a[4] + a[1][a[3]]; })();
    return e.onclick = function() { f(a[3] = (a[3] + 1) % a[1].length); };
  };
  for (_i = 0, _len = s.length; _i < _len; _i++) { a = s[_i]; _fn(a); }

  $('step-2').onclick = function() {
    $('step-2').style.display = 'none';
    $('step-3').style.display = 'block';
    return init(s[0][3], s[1][3], s[2][3], s[3][3]);
  };

  // ... (keep the rest of your file the same)
}).call(this);
